Make it work with dnsmasq on master node Be more verbose Enable variable value check for user inputs

diff --git a/kerrighedize b/kerrighedize
--- a/kerrighedize
+++ b/kerrighedize
@@ -19,6 +19,18 @@ function k_clean
     rm -f ${k_valuesoutput_tmp}
 }
 
+function k_check_root
+{
+    echo -n "Check if user is root... "
+    if [ 0 -ne $(id -u) ]
+    then
+	echo "failed"
+	exit 1
+    else
+	echo "ok"
+    fi
+}
+
 #
 # Load a module
 #
@@ -31,7 +43,6 @@ function k_load
     fi
 	
     module=$1
-    #echo -n "Loading module $module... "
 
     if [ -f /etc/debian_version ]
     then
@@ -59,17 +70,24 @@ function k_load
 
 function usage
 {
-    echo "Usage: $0 [-h] [-I] [-i default.in] [-o default.out]"
+    echo "Usage: $0 [-h] [-I] [-i conf.in] [-o conf.out]"
     echo "  -h   : print this help"
     echo "  -I   : always ask questions"
-    echo "  -i   : load variables value from this file"
-    echo "  -o   : write values to this file for further deployment"
+    echo "  -i   : load config from this file"
+    echo "  -o   : write config to this file for further deployment"
+    echo "  -d   : install dhcp on this server (override config file)"
 }
 
+export dhcp_enable=
 export interactive=
 export valueinput=
 export valueoutput=
-while getopts  "hIi:o:" flag
+
+# Load bootstrap modules
+k_load log
+k_load common
+
+while getopts  "hIi:o:d" flag
 do
     case $flag in
 	h)
@@ -90,6 +108,10 @@ do
 	o)
 	    valuesoutput=$OPTARG
 	    ;;
+	d)
+	    dhcp_enable=1
+	    k_save_var dhcp_enable 1
+	    ;;
 	*)
 	    usage
 	    exit 1
@@ -97,20 +119,23 @@ do
     esac
 done
 
+k_check_root
+
 # Load modules
-k_load log
-k_load common
 k_load install
 k_load packages
+k_load dhcp
 k_load nfs
 k_load tftp
 k_load pxe
 k_load bootloader
 k_load misc
 
+k_dhcp_init
+
 # Run steps
-k_check_root
 k_step_install
+[ ${dhcp_enable} -eq 1 ] && k_step_dhcp
 k_step_nfsserver
 k_step_tftp
 k_step_pxe
diff --git a/lib/common b/lib/common
--- a/lib/common
+++ b/lib/common
@@ -1,22 +1,13 @@
 #!/bin/bash -e
 #
-# common functions 
+# common functions
 dft_valueinput=${basedir}/var/vars.default
+dft_valuecheck=${basedir}/var/vars.check
 dft_msg=${basedir}/var/vars.msg
 
 valueinput=${valueinput:-${dft_valueinput}}
 
-function k_check_root
-{
-    k_log_progress "Check if user is root"
-    if [ 0 -ne $(id -u) ]
-    then
-	k_log_error
-	exit 1
-    else
-	k_log_success
-    fi
-}
+[ -e ${dft_valuecheck} ] && . ${dft_valuecheck}
 
 function k_load_var_saved
 {
@@ -57,6 +48,14 @@ function k_load_var_user
     local value
     local msg=$(k_var_message ${name})
     read -e -p "${msg}> " value
+    value=$(echo "${value}" | sed 's/^\s*\(.*\)\s*/\1/')
+    if set | egrep -q "^k_check_var_${name} ()"; then
+	while ! eval "k_check_var_${name} ${value}"; do
+	    echo "${name}: incorrect value"
+	    read -e -p "${msg}> " value
+	    value=$(echo "${value}" | sed 's/^\s*\(.*\)\s*/\1/')
+	done
+    fi
     eval export ${name}=\"${value}\"
 }
 
@@ -87,6 +86,19 @@ function k_var_message
     echo ${msg}
 }
 
+function k_save_var
+{
+    if [ -z "${1}" -a -z "${2}" ]
+    then
+	echo "k_load_var_file: missing argument" >&2
+	exit 1
+    fi
+    name="${1}"
+    value="${2}"
+
+    echo "${name} ${value}" >> ${k_valuesoutput_tmp}
+}
+
 function k_load_var
 {
     if [ -z "${1}" ]
@@ -109,8 +121,56 @@ function k_load_var
 	    k_load_var_user ${name}
 	fi
 
-	# Save value
-	echo "${name} $(eval echo \$${name})" >> ${k_valuesoutput_tmp}
+	k_save_var "${name}" "$(eval echo \$${name})"
     fi
     eval export ${name}="\$${name}"
+}
+
+#
+# IP manipulation functions
+# Asssume all networks are /24
+#
+function k_ip_split
+{
+    echo $1 | tr '.' ' '
+}
+
+function k_ip_join
+{
+    echo "$1.$2.$3.$4"
+}
+
+# First address of network ($1)
+function k_ip_first
+{
+    local network=( $(k_ip_split $1) )
+    network[3]=1
+
+    k_ip_join ${network[@]}
+}
+
+function k_ip_last
+{
+    local network=( $(k_ip_split $1) )
+    network[3]=254
+
+    k_ip_join ${network[@]}
+}
+
+# Increment an IP ($1) with step ($2)
+# Return 0 on success, 1 if out of bounds
+function k_ip_incr
+{
+    local ip=( $(k_ip_split $1) )
+    local i=$2
+    local ret=0
+
+    ip[3]=$(( ${ip[3]}+i ))
+    if [ 255 -le ${ip[3]} ]; then
+	ret=1
+    else
+	k_ip_join ${ip[@]}
+    fi
+
+    return $ret
 }
